version: '3'
services:
  backend:
    build: .
    ports:
    - "2018:2018"
    restart: always
  frontend:
    image: ilankumaran/frontendkalpatharu:1.0.0
    ports:
    - "3000:3000"
    restart: always
  mongo:
    image: mongo
    ports: 
    - "27017:27017"
    volumes:
    - ./data:/data/db
